### ISSUE TITLE
horrendously out of date and doesn't work

### ISSUE THREAD

**Issue by dennisbenner** [petr7555/rasa-dev-tutorial#7]
`Failed to validate 'C:\Projects\rasa-dev-tutorial\domain.yml'.` 
doman.yml format has changed, e.g.:
```
version: "3.1"
slots:
   email:
      type: text
      mappings:
      - type: from_entity
         entity: email
forms:
   newsletter_form:
      required_slots:
         - email
```
custom actions fail, even when integrated into an up-to-date project the issue persists among others..
